spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC
    username: root
    password: 123455
  resources:
    static-locations: classpath:/templates/
  mvc:
    view:
      suffix: .html
server:
  port: 9000


mybatis:
  mapper-locations: classpath:mapper/*.xml